CRM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls'))
]

mysite/urls.py
from django.urls import path
from . import views

app_name = 'mysite'

urlpatterns = [
    path('', views.home, name='home'),
    # path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('change_password/', views.change_password, name='change_password'),
    path('<int:pk>/', views.view_record, name='view_record'),
    path('add_record/', views.add_record, name='add_record'),
    path('<int:pk>/delete_record', views.delete_record, name='delete_record'),
    path('<int:pk>/update_record', views.update_record, name='update_record'),
]

mysite/models.py
from django.db import models

# Create your models here.

class Record(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=20)

    def __str__(self):
        return (f"{self.first_name} {self.last_name}")
        

mysite/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms
from .models import Record

class SignUpForm(UserCreationForm):
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Email Address"}))
	first_name = forms.CharField(label="", max_length=50, widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "First Name"}))
	last_name = forms.CharField(label="", max_length=50, widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Last Name"}))
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = ''
		self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['password1'].label = ''
		self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

		self.fields['password2'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
		self.fields['password2'].label = ''
		self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'	

class ChangePasswordForm(PasswordChangeForm):

	def __init__(self, *args, **kwargs):
		super(ChangePasswordForm, self).__init__(*args, **kwargs)
		self.fields['old_password'].widget.attrs['class'] = 'form-control'
		self.fields['old_password'].widget.attrs['placeholder'] = 'Old password'
		self.fields['old_password'].label = ''

		self.fields['new_password1'].widget.attrs['class'] = 'form-control'
		self.fields['new_password1'].widget.attrs['placeholder'] = 'New password'
		self.fields['new_password1'].label = ''

		self.fields['new_password2'].widget.attrs['class'] = 'form-control'
		self.fields['new_password2'].widget.attrs['placeholder'] = 'Confirm new password'
		self.fields['new_password2'].label = ''

class AddRecordForm(forms.ModelForm):
	first_name = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "First Name", "class": "form-control"}), label="")
	last_name = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "Last Name", "class": "form-control"}), label="")
	email = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "Email", "class": "form-control"}), label="")
	phone = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "Phone", "class": "form-control"}), label="")
	address = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "Address", "class": "form-control"}), label="")
	city = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "City", "class": "form-control"}), label="")
	state = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "State", "class": "form-control"}), label="")
	zipcode = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "Zipcode", "class": "form-control"}), label="")
	
	class Meta:
		model = Record
		fields = '__all__'

mysite/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from django.urls import reverse
from .forms import SignUpForm, ChangePasswordForm, AddRecordForm
from .models import Record
# Create your views here.



def home(request):

    records = Record.objects.all()

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        # Authenticate
        user = authenticate(request, username=username,password=password)
        print(username, password)
        if user is not None:
            login(request, user)
            messages.success(request, "You have been logged in")
            return HttpResponseRedirect(reverse('mysite:home'))
        else:
            messages.warning(request, "There was an error logging in. Please try again!")
            return HttpResponseRedirect(reverse('mysite:home'))

    else:
        return render(request, 'mysite/home.html', {'records' : records})

    
def logout_user(request):
    logout(request)
    messages.success(request, "You have been logged out.")
    return HttpResponseRedirect(reverse('mysite:home'))

def register_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, 'You have successfully registered')
            return HttpResponseRedirect(reverse('mysite:home'))
    else:
        form = SignUpForm()
        return render(request, 'mysite/register.html', {'form': form})

def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password is updated successfully')
            return HttpResponseRedirect(reverse('mysite:home'))
        else:
            messages.warning(request, 'Please correct the error')

    else:
        form = ChangePasswordForm(request.user)

    return render(request, 'mysite/change_password.html', {'form': form})

def view_record(request, pk):
    if not request.user.is_authenticated:
        messages.warning(request, 'You have to log in before having access to that page')
        return HttpResponseRedirect(reverse('mysite:home'))
    else:
        try:
            record = Record.objects.get(pk=pk)
        except Record.DoesNotExist:
            raise Http404("Record Not Found")
        return render(request, 'mysite/record.html', {'customer_record': record})
        
def add_record(request):
    if not request.user.is_authenticated:
        messages.warning(request, 'You have to log in before having access to that page')
        return HttpResponseRedirect(reverse('mysite:home'))
    else:
        if request.method == 'POST':
            form = AddRecordForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Record added...')
                return HttpResponseRedirect(reverse('mysite:home'))

        form = AddRecordForm()
        return render(request, 'mysite/add_record.html', {'form': form})

def delete_record(request, pk):
    if not request.user.is_authenticated:
        messages.warning(request, 'You have to log in before having access to that page')
        return HttpResponseRedirect(reverse('mysite:home'))
    else:
        try:
            record = Record.objects.get(pk=pk)
        except Record.DoesNotExist:
            raise Http404("Record Not Found")
        
        record.delete()
        messages.success(request, 'Record Deleted Successfully')
        return HttpResponseRedirect(reverse('mysite:home'))

def update_record(request, pk):
    if not request.user.is_authenticated:
        messages.warning(request, 'You have to log in before having access to that page')
        return HttpResponseRedirect(reverse('mysite:home'))
    else:
        try:
            record = Record.objects.get(pk=pk)
        except Record.DoesNotExist:
            raise Http404('Record Not Found')

        if request.method == 'POST':
            form = AddRecordForm(request.POST, instance=record)
            if form.is_valid():
                form.save()
                messages.success(request, 'Record Has Been Updated')
                return HttpResponseRedirect(reverse('mysite:view_record', args=(pk, )))
        else:
            form = AddRecordForm(instance=record)
            return render(request, 'mysite/update_record.html', {'form': form})

mysite/templates/mysite/add_record.html
{% extends 'mysite/base.html' %}

{% block content %}
    <form action="{% url 'mysite:add_record' %}" method="POST">
        {% csrf_token %}

        {{form.as_p}}

        <button type="submit" class="btn btn-secondary">
            Add record
        </button>
    </form>
{% endblock content %}

mysite/templates/mysite/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    {% include 'mysite/navbar.html' %}


    <div class="container">
        <br>

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}}" role="alert">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

mysite/templates/mysite/change_password.html
{% extends 'mysite/base.html' %}

{% block content %}
    <form action="{% url 'mysite:change_password' %}" method="POST">
        {% csrf_token %}

        {{form.as_p}}

        <br>
        <button type="submit" class="btn btn-secondary">
            Change
        </button>
    </form>

{% endblock content %}

mysite/templates/mysite/home.html
{% extends 'mysite/base.html' %}

{% block content %}

    {% if user.is_authenticated %}
        {% if records %}
        <table class="table table-striped table-hover table-bordered">
            <thead class="table-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Address</th>
                <th scope="col">City</th>
              </tr>
            </thead>
            <tbody>
                {% for record in records %}
                <tr>
                    <th scope="row"><a href="{% url 'mysite:view_record' record.id %}">{{record.id}}</a></th>
                    <td>{{record.first_name}}</td>
                    <td>{{record.last_name}}</td>
                    <td>{{record.email}}</td>
                    <td>{{record.phone}}</td>
                    <td>{{record.address}}</td>
                    <td>{{record.city}}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
        
        {% else %}
            <h1>Please add some records</h1>
        {% endif %}
    {% else %}
    <div class="col-md-6 offset-md-3">
        <h1>Login</h1>
        <br>
        <form method="POST" action="{% url 'mysite:home' %}">
            {% csrf_token %}
            <div class="mb-3">
                <input type="text" class="form-control" name="username" placeholder="username" required>
            </div>
            <div class="mb-3">
                <input type="password" class="form-control" name="password" placeholder="password" required>
            </div>
            <br>
            <button type="submit" class="btn btn-secondary">Login</button>
        </form>
    </div>
    {% endif %}
    
{% endblock%}

mysite/templates/mysite/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'mysite:home' %}">Django CRM</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'mysite:logout' %}" class="nav-link">Log out</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'mysite:change_password' %}" class="nav-link">Change your password</a>
              </li>
                <li class="nav-item">
                  <a href="{% url 'mysite:add_record' %}" class="nav-link">Add customer record</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'mysite:home' %}" class="nav-link">Log in</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'mysite:register' %}" class="nav-link">Register</a>
                </li>
            {% endif %}
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li> {% endcomment %}
          
          </li>
        </ul>

      </div>
    </div>
  </nav>

mysite/templates/mysite/record.html
{% extends 'mysite/base.html' %}
{% block content %}



<div class="card">
  <div class="card-header"><strong>
    	{{ customer_record.first_name }} 
		{{ customer_record.last_name }}</strong>
  </div>
  <div class="card-body">



<p class="card-text">
<strong>Email: </strong>{{ customer_record.email }}</p>

<p class="card-text">
<strong>Phone: </strong>{{ customer_record.phone }}
</p>

<p class="card-text">
<strong>Address: </strong>{{ customer_record.address }}</p>

<p class="card-text">
<strong>City: </strong>{{ customer_record.city }}</p>

<p class="card-text">
<strong>State: </strong>{{ customer_record.state }}</p>

<p class="card-text">
<strong>Zipcode: </strong>{{ customer_record.zipcode }}</p>

<p class="card-text">
<strong>Create At: </strong>{{ customer_record.created_at }}</p>

<p class="card-text">
<strong>ID: </strong>{{ customer_record.id }}</p>
    
    
  </div>
</div>

<br/><br/>
<a href="{% url 'mysite:home' %}" class="btn btn-secondary">Back</a>

<a href="{% url 'mysite:delete_record' customer_record.id %}" class="btn btn-danger">Delete</a>

<a href="{% url 'mysite:update_record' customer_record.id %}" class="btn btn-secondary">Update Record</a> 
		

{% endblock %}

mysite/templates/mysite/register.html
{% extends 'mysite/base.html' %}

{% block content %}
    <form action="{% url 'mysite:register' %}" method="POST">
        {% csrf_token %}

        {{form.as_p}}

        <br>
        <button type="submit" class="btn btn-secondary">
            Register
        </button>
    </form>

{% endblock content %}

mysite/templates/mysite/update_record.html
{% extends 'mysite/base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="btn btn-primary">Update</button>
    </form>
{% endblock content %}
    